[#24] register
wafflestudio19-5/team7-server pull request #45
Opened 2021-12-30 04:28 UTC by yeonsumia

- send register confirm email via POST /user/
- enable user via GET /verify/{token}/
- register (add user infos) via POST /user/signup/

## PR 타입
- [ ] 새로운 기능 추가
- [ ] 버그 수정
- [ ] CI / CD
- [ ] 기타 설정

## PR 설명
수정 사항에 관한 간단한 요약을 작성해주세요.

Resolves #<issue No.>

## 체크리스트
- [ ] 작성한 코드가 프로젝트의 스타일과 맞습니다.
- [ ] 코드의 이해에 필요한 주석을 작성했습니다.
- [ ] 수정 사항이 새로운 경고를 발생시키지 않습니다.
- [ ] 기존 및 신규 단위 테스트를 통과했습니다.
- [ ] (필요한 경우) 문서를 적절하게 수정했습니다.

2021-12-30 04:49 UTC, WallabyG requested changes
로컬에서 conflict 해결 후 다시 커밋해주세요.
Slack 참고해서 ktlint 체크까지 확인하셔야 할 것 같습니다.

2021-12-30 10:08 UTC, WallabyG requested changes
.DS_store이나 .idea는 git에서 지워주시면 좋을 것 같습니다.

API에서 trailing slash 다 빼주셔야 할 것 같아요.

굳이 필요하지 않다면 nullable을 사용하지 않는 것이 좋을 것 같습니다.

2021-12-30 10:08 UTC, wallabyg commented on waflog/scripts/deploy/deploy.sh
> -
위 코드와 역할이 겹치긴 하는데, 일부러 빼신 이유가 있는 건가요?

2021-12-30 10:08 UTC, WallabyG commented on waflog/src/main/kotlin/com/wafflestudio/waflog/domain/user/model/User.kt
> +    var username: String? = "",
name, userId, username의 역할과 이름을 명확하게 정해야 할 것 같습니다.
혹시 어떻게 사용하는 것이 좋다고 생각하세요?

2021-12-30 17:45 UTC, nemga123 commented on waflog/src/main/kotlin/com/wafflestudio/waflog/domain/user/model/User.kt
intro는 short와 long을 제외하고 어떤 data인가요?

2021-12-30 17:45 UTC, nemga123 commented on waflog/src/main/kotlin/com/wafflestudio/waflog/domain/user/model/User.kt
> +    var username: String? = "",
제가 기억하기론 name이나 id와 같은 이름이 사용되는 데이터는 2가지였던 걸로 기억하는데, 하나는 포스트 들어가면 제목 바로 아래에 뜨는 아이디를 userId, 아래 user image와 같이 뜨는 아이디가 별명에 더 가까워서 그거를 username과 같은 것으로 설정하는게 나을 것 같습니다.

2021-12-30 17:45 UTC, nemga123 commented on waflog/src/main/kotlin/com/wafflestudio/waflog/global/auth/service/AuthService.kt
> +
signupEmail에서 user를 db에 저장하면 email을 받고 회원가입 링크를 클릭하지 않은 사람들도 db에 저장되는 문제가 생길 것 같습니다.

2021-12-30 19:26 UTC, WallabyG commented on waflog/src/main/kotlin/com/wafflestudio/waflog/global/auth/service/AuthService.kt
> +
user 대신 인증을 위한 새로운 모델을 사용하는 것이 좋아보입니다.

2021-12-31 04:50 UTC, yeonsumia commented on waflog/src/main/kotlin/com/wafflestudio/waflog/global/auth/service/AuthService.kt
> +
enabled 로 회원가입 여부를 알 수 있는데 괜찮지 않나요?

2021-12-31 04:59 UTC, yeonsumia commented on waflog/src/main/kotlin/com/wafflestudio/waflog/global/auth/service/AuthService.kt
> +
> user 대신 인증을 위한 새로운 모델을 사용하는 것이 좋아보입니다.

새로운 모델은 db에 저장하지 않도록 구현해야 한다는 말씀이신가요?

2021-12-31 05:34 UTC, WallabyG commented on waflog/src/main/kotlin/com/wafflestudio/waflog/global/auth/service/AuthService.kt
> +
user DB에는 회원가입이 완료된 사용자만 저장하는게 좋을 것 같아서요.
email이랑 token 정도만 가지는 인증 전용 모델을 만들면 어떨까합니다.

2022-01-01 11:00 UTC, yeonsumia commented on waflog/src/main/kotlin/com/wafflestudio/waflog/domain/user/model/User.kt
> +    var username: String? = "",
회원 가입 시
이름 --> userName
아이디 --> userId
한 줄 소개 --> intro
로 코드 작성하였습니다.

2022-01-01 11:02 UTC, yeonsumia commented on waflog/src/main/kotlin/com/wafflestudio/waflog/domain/user/model/User.kt
회원 가입 시 한 줄 소개에 해당하는 값입니다.

2022-01-01 11:03 UTC, yeonsumia commented on waflog/scripts/deploy/deploy.sh
> -
conflict 해결 과정에서 지워진 것 같습니다. 원상복구 해두었습니다.

2022-01-01 11:04 UTC, yeonsumia commented
> .DS_store이나 .idea는 git에서 지워주시면 좋을 것 같습니다.
> 
> API에서 trailing slash 다 빼주셔야 할 것 같아요.
> 
> 굳이 필요하지 않다면 nullable을 사용하지 않는 것이 좋을 것 같습니다.

임시로 nullable로 해두었는데, 추후에 불필요하다면 제거하겠습니다.

2022-01-01 12:58 UTC, WallabyG commented on waflog/src/main/kotlin/com/wafflestudio/waflog/domain/user/model/User.kt
한 줄 소개는 shortIntro를 사용하면 될 것 같습니다!

2022-01-01 13:00 UTC, yeonsumia commented on waflog/src/main/kotlin/com/wafflestudio/waflog/domain/user/model/User.kt
넵 알겠습니다

2022-01-01 13:01 UTC, WallabyG commented on waflog/src/main/kotlin/com/wafflestudio/waflog/domain/user/model/User.kt
> +    var username: String? = "",
userName이랑 userId로 구분하는 것 좋습니다.
백엔드에서 혼동 없이 사용하면 문제 없을 것 같네요.

2022-01-01 13:21 UTC, WallabyG reviewed
제가 이해한대로는 회원가입과 로그인이 모두 이메일을 통해 이루어지는 것 같은데 맞나요?

2022-01-01 13:21 UTC, WallabyG commented on waflog/src/main/kotlin/com/wafflestudio/waflog/domain/user/model/User.kt
> +    val updateNotification: Boolean? = false,
생성자에서 빈 문자열로 기본값을 설정하면 굳이 nullable을 사용하지 않아도 될 것 같습니다.

2022-01-01 13:21 UTC, WallabyG commented on waflog/src/main/kotlin/com/wafflestudio/waflog/global/auth/dto/ExistUserDto.kt
> +}
DB에서 email이 중복되는 경우라면, 409 conflict exception response를 반환하는 게 좋을 것 같습니다.

2022-01-01 13:21 UTC, WallabyG commented on waflog/src/main/kotlin/com/wafflestudio/waflog/global/auth/model/VerificationToken.kt
> +    val user: User,
user.enabled를 사용하지 않는 방식으로 수정한 것으로 기억하는데, 이 user는 어디에 사용하는 건가요?
혹시 로그인에 필요한 column인가요?

2022-01-01 13:21 UTC, WallabyG commented on waflog/src/main/kotlin/com/wafflestudio/waflog/global/auth/service/AuthService.kt
> +        }
kotlinic하게 ```?.```을 사용해봅시다!

2022-01-01 13:21 UTC, WallabyG commented on waflog/src/main/kotlin/com/wafflestudio/waflog/global/config/SecurityConfig.kt
> +            .antMatchers(HttpMethod.POST, "/api/v1/auth/user/").permitAll()
user 뒤에 trailing slash가 남아있습니다.

2022-01-01 13:28 UTC, WallabyG commented
> 제가 이해한대로는 회원가입과 로그인이 모두 이메일을 통해 이루어지는 것 같은데 맞나요?

아 아직 회원가입 부분만 구현하신거였죠! 착각했습니다.

2022-01-01 13:35 UTC, yeonsumia commented on waflog/src/main/kotlin/com/wafflestudio/waflog/global/auth/model/VerificationToken.kt
> +    val user: User,
넵 아마 로그인에 사용할 것 같아서 지우지 않고 남겨 두었습니다.

2022-01-01 13:36 UTC, yeonsumia commented
> > 제가 이해한대로는 회원가입과 로그인이 모두 이메일을 통해 이루어지는 것 같은데 맞나요?
> 
> 아 아직 회원가입 부분만 구현하신거였죠! 착각했습니다.

넵 둘다 이메일로 이루어지는 것이 맞습니다

2022-01-01 13:37 UTC, yeonsumia commented on waflog/src/main/kotlin/com/wafflestudio/waflog/global/config/SecurityConfig.kt
> +            .antMatchers(HttpMethod.POST, "/api/v1/auth/user/").permitAll()
넵 확인했습니다.

2022-01-01 13:37 UTC, yeonsumia commented on waflog/src/main/kotlin/com/wafflestudio/waflog/domain/user/model/User.kt
> +    val updateNotification: Boolean? = false,
넵 확인했습니다.

2022-01-01 13:38 UTC, WallabyG commented on waflog/src/main/kotlin/com/wafflestudio/waflog/global/auth/model/VerificationToken.kt
> +    val user: User,
그러면 로그인은 "메일 발송 - 링크 클릭 - 인증 후 JWT 발급" 이렇게 이루어지는 건가요?

2022-01-01 13:39 UTC, yeonsumia commented on waflog/src/main/kotlin/com/wafflestudio/waflog/global/auth/model/VerificationToken.kt
> +    val user: User,
넵 맞습니다.

2022-01-01 13:47 UTC, yeonsumia commented on waflog/src/main/kotlin/com/wafflestudio/waflog/global/auth/service/AuthService.kt
> +        }
넵 확인했습니다!

2022-01-01 13:51 UTC, yeonsumia commented on waflog/src/main/kotlin/com/wafflestudio/waflog/global/auth/dto/ExistUserDto.kt
> +}
아 이 dto는 frontend 쪽에서 컴포넌트를 띄울 때 필요한 boolean 값이어서 반환해준 것이었습니다.
회원가입 과정에서는 이미 DB에 동일 email 유저가 있다면 login 절차로 redirect 됩니다.

2022-01-01 14:21 UTC, WallabyG commented on waflog/src/main/kotlin/com/wafflestudio/waflog/global/auth/service/AuthService.kt
> +        userRepository.save(user)
repository에서 구현한 방식이 먼저 ```findByEmail```로 토큰을 찾은 뒤, 토큰의 id로 삭제하는 것으로 기억합니다.
그렇다면 service에서 먼저 토큰을 찾아두고, null일때 exception 처리를 한 뒤 ```deleteById```를 사용하는 것은 어떨까요?
DB 쿼리 횟수는 같은데, exception 처리가 조금 더 편할 것 같습니다.

2022-01-01 14:21 UTC, WallabyG commented on waflog/src/main/kotlin/com/wafflestudio/waflog/domain/user/dto/UserDto.kt
> +            username = user.userName,
DTO의 name을 userId로 바꿔야 할 것 같습니다.

2022-01-01 14:21 UTC, WallabyG commented on waflog/src/main/kotlin/com/wafflestudio/waflog/domain/post/repository/PostRepository.kt
> +            "(p.title LIKE %:title% OR p.content LIKE %:content% OR p.user.userName = :username)"
이전에 사용하던 username이 현재 userId입니다.
적당히 수정해주어야 할 것 같습니다.

2022-01-01 14:26 UTC, WallabyG commented on waflog/src/main/kotlin/com/wafflestudio/waflog/domain/user/dto/UserDto.kt
> +            username = user.userName,
사실 userId를 사용하면 굳이 username이라는 변수명을 사용할 필요가 없습니다.
사용자의 id (e.g. WallabyG)를 userId로, 사용자의 이름(윤창민)을 name으로 사용해도 되지 않을까요?
이 경우 모델과 DTO의 적절한 수정이 필요할 듯 합니다.
username이 userId가 되는 것이니, DB의 unique annotation 위치도 바꿔야 하겠죠.

2022-01-01 14:55 UTC, WallabyG commented on waflog/src/main/kotlin/com/wafflestudio/waflog/global/auth/model/VerificationTokenUser.kt
> +) : BaseTimeEntity()
이 부분이 VerificationTokenUser가 맞나요? 내용 상으로는 현재 VerificationToken과 이 모델의 이름이 바뀐 것 같아서요.

2022-01-01 15:01 UTC, WallabyG reviewed
AuthService의 실행 순서를 잘 이해했는지 궁금합니다.
1. 유저가 이메일을 입력하고 회원가입/로그인을 클릭하면 ```signupEmail```을 통해 이메일로 링크를 보내고, 
2. 그 링크를 클릭하면 토큰을 통해 ```verifyAccount```를 실행하고,
3. 이후 회원가입에 필요한 정보를 입력받고 실제로 회원가입을 하는 ```signup```을 실행하는 것 같습니다.

2에서 3으로 넘어갈때, 인증이 어떻게 이루어지는 것인가요?
```TokenNotFoundException```이 발생하지 않으면 정상적인 인증으로 처리하여 자동으로 ```/auth/user/info```로 요청을 보내게 되나요?

2022-01-01 15:06 UTC, WallabyG commented
> AuthService의 실행 순서를 잘 이해했는지 궁금합니다.
> 
> 1. 유저가 이메일을 입력하고 회원가입/로그인을 클릭하면 `signupEmail`을 통해 이메일로 링크를 보내고,
> 2. 그 링크를 클릭하면 토큰을 통해 `verifyAccount`를 실행하고,
> 3. 이후 회원가입에 필요한 정보를 입력받고 실제로 회원가입을 하는 `signup`을 실행하는 것 같습니다.
> 
> 2에서 3으로 넘어갈때, 인증이 어떻게 이루어지는 것인가요? `TokenNotFoundException`이 발생하지 않으면 정상적인 인증으로 처리하여 자동으로 `/auth/user/info`로 요청을 보내게 되나요?

```https://d259mvltzqd1q5.cloudfront.net/register?code=$token``` 이 링크의 프론트엔드에서 해당 작업을 담당하는 것 같아 보입니다..
프론트랑 연관된 부분이니까 이해하기 쉽지 않네요..

2022-01-01 15:19 UTC, yeonsumia commented on waflog/src/main/kotlin/com/wafflestudio/waflog/global/auth/model/VerificationTokenUser.kt
> +) : BaseTimeEntity()
아 네 지적해주신 부분이 맞습니다. 확인했습니다.

2022-01-01 15:24 UTC, yeonsumia commented
> > AuthService의 실행 순서를 잘 이해했는지 궁금합니다.
> > 
> > 1. 유저가 이메일을 입력하고 회원가입/로그인을 클릭하면 `signupEmail`을 통해 이메일로 링크를 보내고,
> > 2. 그 링크를 클릭하면 토큰을 통해 `verifyAccount`를 실행하고,
> > 3. 이후 회원가입에 필요한 정보를 입력받고 실제로 회원가입을 하는 `signup`을 실행하는 것 같습니다.
> > 
> > 2에서 3으로 넘어갈때, 인증이 어떻게 이루어지는 것인가요? `TokenNotFoundException`이 발생하지 않으면 정상적인 인증으로 처리하여 자동으로 `/auth/user/info`로 요청을 보내게 되나요?
> 
> `https://d259mvltzqd1q5.cloudfront.net/register?code=$token` 이 링크의 프론트엔드에서 해당 작업을 담당하는 것 같아 보입니다.. 프론트랑 연관된 부분이니까 이해하기 쉽지 않네요..

메일에서 위 링크를 클릭하면 frontend에서 backend로 verify 요청을 보내고, exception이 발생하지 않으면 register 화면(이름, 아이디, 한줄 소개 작성하는 화면)을 띄웁니다. 사용자가 입력한 뒤 submit하면 POST /auth/user/info를 요청합니다.

2022-01-01 15:45 UTC, WallabyG commented on waflog/src/main/kotlin/com/wafflestudio/waflog/global/auth/model/VerificationToken.kt
> +@Table(name = "token_user")
이 테이블은 원래 그대로가 맞지 않을까요?

2022-01-01 15:46 UTC, WallabyG commented on waflog/src/main/kotlin/com/wafflestudio/waflog/global/auth/service/AuthService.kt
> +        val verificationTokenUser = VerificationToken(email, token)
변수명도 같이 바꿔주시면 좋을 것 같아요!

2022-01-01 15:47 UTC, yeonsumia commented on waflog/src/main/kotlin/com/wafflestudio/waflog/global/auth/model/VerificationToken.kt
> +@Table(name = "token_user")
아 넵 맞습니다.

2022-01-01 15:47 UTC, yeonsumia commented on waflog/src/main/kotlin/com/wafflestudio/waflog/global/auth/service/AuthService.kt
> +        val verificationTokenUser = VerificationToken(email, token)
넵 확인했습니다.

2022-01-01 16:00 UTC, WallabyG approved these changes
고생하셨습니다!
로그인 부분도 잘 부탁드립니다 :)

2022-01-01 16:07 UTC, merged